# Generated by Django 4.2.7 on 2023-11-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
        ('Callboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='advert',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.gallery', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='advert',
            name='slug',
            field=models.SlugField(default='0', max_length=200, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='txt'),
        ),
        migrations.AlterField(
            model_name='dateadvert',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='filteradvert',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
    ]
